FROM node:20.15.0 

WORKDIR /src

COPY . .

RUN npm install -g @angular/cli@18.1.0

EXPOSE 4200

CMD bash -c "npm install --legacy-peer-deps --loglevel verbose && ng serve --host 0.0.0.0 --port 4200 --disable-host-check"